# In _config.yml
title: UPC-205237 Advanced Fluid Mechanics
author: Robert Castilla - UPC CATMech Terrassa
logo: eseiaat-positiu-p3005-interior-blanc.png
copyright: "2022"
repository:
  url: https://github.com/rclUPC/AdvancedFluidMechanics
execute:
  execute_notebooks: force
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    #- amsmath
    - dollarmath
    - colon_fence
sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
            "Ma": "\\mathrm{Ma}"
#        equationNumbers: 
#            autoNumber: "AMS"
#  equationNumbers: { autoNumber: "AMS" } }
# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
latex:
  latex_engine: pdflatex

