# In _config.yml
title: UPC-205237 Advanced Fluid Mechanics
author: Robert Castilla - UPC CATMech Terrassa
logo: logo.png
execute:
  execute_notebooks: force
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence
TeX:
  Macros:
    "Ma": "\\mathrm{Ma}"
# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
