# In _config.yml
title: UPC-205237 Advanced Fluid Mechanics
author: Robert Castilla - UPC CATMech Terrassa
logo: eseiaat-positiu-p3005-interior-blanc.png
copyright: "2023"
repository:
  url: https://github.com/rclUPC/AdvancedFluidMechanics

execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    #- amsmath
    - dollarmath
    - colon_fence
sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
            "Ma": "\\mathrm{Ma}"
#        equationNumbers: 
#            autoNumber: "AMS"
#  equationNumbers: { autoNumber: "AMS" } }
# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib
latex:
  latex_engine: pdflatex

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/rclUPC/AdvancedFluidMechanics  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

